"""initial schema

Revision ID: e35c3942a989
Revises: 
Create Date: 2026-04-28 23:02:39.798255
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# pgvector type — stored as Text placeholder in local dev; patched to Vector(1536) at runtime
_EMBEDDING_TYPE = sa.Text()

# revision identifiers, used by Alembic.
revision: str = 'e35c3942a989'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_name', sa.String(length=400), nullable=False),
    sa.Column('brand_name', sa.String(length=300), nullable=True),
    sa.Column('fssai_license', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('energy_kcal_per_100g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('name_embedding', _EMBEDDING_TYPE, nullable=True, comment='pgvector Vector(1536); populated by embedding worker'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grocery_items_barcode', 'grocery_items', ['barcode'], unique=False)
    op.create_index(op.f('ix_grocery_items_brand_name'), 'grocery_items', ['brand_name'], unique=False)
    op.create_index('ix_grocery_items_category', 'grocery_items', ['category'], unique=False)
    op.create_index('ix_grocery_items_fssai', 'grocery_items', ['fssai_license'], unique=False)
    op.create_index(op.f('ix_grocery_items_fssai_license'), 'grocery_items', ['fssai_license'], unique=False)
    op.create_index('ix_grocery_items_name', 'grocery_items', ['product_name'], unique=False)
    op.create_index(op.f('ix_grocery_items_product_name'), 'grocery_items', ['product_name'], unique=False)
    op.create_table('medicines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('generic_name', sa.String(length=300), nullable=False),
    sa.Column('brand_name', sa.String(length=300), nullable=False),
    sa.Column('dosage_form', sa.Enum('TABLET', 'CAPSULE', 'SYRUP', 'INJECTION', 'CREAM', 'DROPS', 'POWDER', 'PATCH', 'INHALER', 'SUPPOSITORY', 'GEL', 'LOTION', 'OINTMENT', 'SUSPENSION', 'LOZENGE', name='dosage_form_enum'), nullable=False),
    sa.Column('strength', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=300), nullable=False),
    sa.Column('cdsco_license', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('qr_data', sa.Text(), nullable=True),
    sa.Column('name_embedding', _EMBEDDING_TYPE, nullable=True, comment='pgvector Vector(1536); populated by embedding worker'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_barcode'), 'medicines', ['barcode'], unique=True)
    op.create_index('ix_medicines_brand_name', 'medicines', ['brand_name'], unique=False)
    op.create_index('ix_medicines_cdsco', 'medicines', ['cdsco_license'], unique=False)
    op.create_index(op.f('ix_medicines_cdsco_license'), 'medicines', ['cdsco_license'], unique=False)
    op.create_index(op.f('ix_medicines_generic_name'), 'medicines', ['generic_name'], unique=False)
    op.create_index(op.f('ix_medicines_manufacturer'), 'medicines', ['manufacturer'], unique=False)
    op.create_table('product_certifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.Enum('MEDICINE', 'GROCERY', name='product_type_enum'), nullable=False),
    sa.Column('authority', sa.Enum('FSSAI', 'CDSCO', 'ISO', 'AYUSH', 'BIS', 'ORGANIC_INDIA', 'VEGAN_SOCIETY', name='certification_authority_enum'), nullable=False),
    sa.Column('license_number', sa.String(length=200), nullable=False),
    sa.Column('is_valid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'product_type', 'authority', 'license_number', name='uq_product_certification')
    )
    op.create_index('ix_product_certifications_authority', 'product_certifications', ['authority'], unique=False)
    op.create_index('ix_product_certifications_license', 'product_certifications', ['license_number'], unique=False)
    op.create_index(op.f('ix_product_certifications_license_number'), 'product_certifications', ['license_number'], unique=False)
    op.create_index('ix_product_certifications_product', 'product_certifications', ['product_id', 'product_type'], unique=False)
    op.create_index(op.f('ix_product_certifications_product_id'), 'product_certifications', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_certifications_product_type'), 'product_certifications', ['product_type'], unique=False)
    op.create_table('salts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('iupac_name', sa.String(length=500), nullable=True),
    sa.Column('cas_number', sa.String(length=20), nullable=True),
    sa.Column('molecular_formula', sa.String(length=100), nullable=True),
    sa.Column('molecular_weight_g_mol', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cas_number')
    )
    op.create_index(op.f('ix_salts_name'), 'salts', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_user_id', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender_enum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('phone_number IS NOT NULL OR email IS NOT NULL OR whatsapp_user_id IS NOT NULL', name='ck_users_at_least_one_contact'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_whatsapp_user_id'), 'users', ['whatsapp_user_id'], unique=True)
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('whatsapp_user_id', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='message_direction_enum'), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'AUDIO', 'DOCUMENT', 'STICKER', name='message_type_enum'), server_default='TEXT', nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_messages_user_id_created', 'conversation_messages', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_conv_messages_wa_id_created', 'conversation_messages', ['whatsapp_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_direction'), 'conversation_messages', ['direction'], unique=False)
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_whatsapp_user_id'), 'conversation_messages', ['whatsapp_user_id'], unique=False)
    op.create_table('drug_interactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('salt_id_a', sa.UUID(), nullable=False),
    sa.Column('salt_id_b', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('MILD', 'MODERATE', 'SEVERE', 'CONTRAINDICATED', name='interaction_severity_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('clinical_significance', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('salt_id_a < salt_id_b', name='ck_drug_interactions_ordered_pair'),
    sa.ForeignKeyConstraint(['salt_id_a'], ['salts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salt_id_b'], ['salts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salt_id_a', 'salt_id_b', name='uq_drug_interactions_pair')
    )
    op.create_index('ix_drug_interactions_a', 'drug_interactions', ['salt_id_a'], unique=False)
    op.create_index('ix_drug_interactions_b', 'drug_interactions', ['salt_id_b'], unique=False)
    op.create_index(op.f('ix_drug_interactions_salt_id_a'), 'drug_interactions', ['salt_id_a'], unique=False)
    op.create_index(op.f('ix_drug_interactions_salt_id_b'), 'drug_interactions', ['salt_id_b'], unique=False)
    op.create_index('ix_drug_interactions_severity', 'drug_interactions', ['severity'], unique=False)
    op.create_table('grocery_ingredients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('grocery_item_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=400), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('allergen_category', sa.Enum('GLUTEN', 'CRUSTACEANS', 'EGGS', 'FISH', 'PEANUTS', 'SOYBEANS', 'MILK', 'TREE_NUTS', 'CELERY', 'MUSTARD', 'SESAME', 'SULPHITES', 'LUPIN', 'MOLLUSCS', 'COCONUT', 'CORN', 'LATEX', 'OTHER', name='allergen_category_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grocery_item_id'], ['grocery_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grocery_ingredients_allergen', 'grocery_ingredients', ['allergen_category'], unique=False)
    op.create_index(op.f('ix_grocery_ingredients_allergen_category'), 'grocery_ingredients', ['allergen_category'], unique=False)
    op.create_index(op.f('ix_grocery_ingredients_grocery_item_id'), 'grocery_ingredients', ['grocery_item_id'], unique=False)
    op.create_index('ix_grocery_ingredients_item_id', 'grocery_ingredients', ['grocery_item_id'], unique=False)
    op.create_table('medicine_batches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('batch_no', sa.String(length=100), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('barcode', sa.String(length=200), nullable=True),
    sa.Column('qr_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_id', 'batch_no', name='uq_medicine_batch')
    )
    op.create_index(op.f('ix_medicine_batches_barcode'), 'medicine_batches', ['barcode'], unique=True)
    op.create_index(op.f('ix_medicine_batches_batch_no'), 'medicine_batches', ['batch_no'], unique=False)
    op.create_index('ix_medicine_batches_expiry', 'medicine_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_medicine_batches_expiry_date'), 'medicine_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_medicine_batches_medicine_id'), 'medicine_batches', ['medicine_id'], unique=False)
    op.create_table('medicine_salts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('salt_id', sa.UUID(), nullable=False),
    sa.Column('quantity_mg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salt_id'], ['salts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_id', 'salt_id', name='uq_medicine_salts')
    )
    op.create_index(op.f('ix_medicine_salts_medicine_id'), 'medicine_salts', ['medicine_id'], unique=False)
    op.create_index('ix_medicine_salts_salt_id', 'medicine_salts', ['salt_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('doctor_name', sa.String(length=300), nullable=True),
    sa.Column('doctor_registration_no', sa.String(length=100), nullable=True),
    sa.Column('hospital_name', sa.String(length=300), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_user_id'), 'prescriptions', ['user_id'], unique=False)
    op.create_table('user_allergies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('allergen', sa.String(length=200), nullable=False),
    sa.Column('allergen_category', sa.Enum('GLUTEN', 'CRUSTACEANS', 'EGGS', 'FISH', 'PEANUTS', 'SOYBEANS', 'MILK', 'TREE_NUTS', 'CELERY', 'MUSTARD', 'SESAME', 'SULPHITES', 'LUPIN', 'MOLLUSCS', 'COCONUT', 'CORN', 'LATEX', 'OTHER', name='allergen_category_enum'), nullable=True),
    sa.Column('severity_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'allergen', name='uq_user_allergies_user_allergen')
    )
    op.create_index('ix_user_allergies_category', 'user_allergies', ['allergen_category'], unique=False)
    op.create_index('ix_user_allergies_user_id', 'user_allergies', ['user_id'], unique=False)
    op.create_table('user_drug_reactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('salt_id', sa.UUID(), nullable=False),
    sa.Column('reaction_description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('MILD', 'MODERATE', 'SEVERE', 'LIFE_THREATENING', name='reaction_severity_enum'), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salt_id'], ['salts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_drug_reactions_salt_id', 'user_drug_reactions', ['salt_id'], unique=False)
    op.create_index(op.f('ix_user_drug_reactions_user_id'), 'user_drug_reactions', ['user_id'], unique=False)
    op.create_table('user_health_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dietary_preference', sa.Enum('VEGETARIAN', 'VEGAN', 'NON_VEGETARIAN', 'JAIN', 'HALAL', 'KOSHER', 'GLUTEN_FREE', name='dietary_preference_enum'), nullable=True),
    sa.Column('blood_group', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', 'UNKNOWN', name='blood_group_enum'), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('health_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_health_profiles_user_id'), 'user_health_profiles', ['user_id'], unique=True)
    op.create_table('user_medical_conditions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('condition_name', sa.String(length=300), nullable=False),
    sa.Column('icd_10_code', sa.String(length=10), nullable=True),
    sa.Column('diagnosed_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_conditions_icd10', 'user_medical_conditions', ['icd_10_code'], unique=False)
    op.create_index('ix_user_conditions_user_id', 'user_medical_conditions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_medical_conditions_user_id'), 'user_medical_conditions', ['user_id'], unique=False)
    op.create_table('medicine_scan_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('medicine_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('barcode_data', sa.String(length=500), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('authenticity_verdict', sa.Enum('VERIFIED', 'SUSPICIOUS', 'EXPIRED', 'UNKNOWN', name='authenticity_verdict_enum'), nullable=False),
    sa.Column('verdict_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('verdict_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['medicine_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_scan_events_authenticity_verdict'), 'medicine_scan_events', ['authenticity_verdict'], unique=False)
    op.create_index(op.f('ix_medicine_scan_events_batch_id'), 'medicine_scan_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_medicine_scan_events_medicine_id'), 'medicine_scan_events', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_medicine_scan_events_user_id'), 'medicine_scan_events', ['user_id'], unique=False)
    op.create_index('ix_scan_events_batch_id', 'medicine_scan_events', ['batch_id'], unique=False)
    op.create_index('ix_scan_events_medicine_id', 'medicine_scan_events', ['medicine_id'], unique=False)
    op.create_index('ix_scan_events_scanned_at', 'medicine_scan_events', ['scanned_at'], unique=False)
    op.create_index('ix_scan_events_user_id', 'medicine_scan_events', ['user_id'], unique=False)
    op.create_index('ix_scan_events_verdict', 'medicine_scan_events', ['authenticity_verdict'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('dosage_instructions', sa.Text(), nullable=False),
    sa.Column('intake_frequency', sa.Enum('ONCE_DAILY', 'TWICE_DAILY', 'THRICE_DAILY', 'FOUR_TIMES_DAILY', 'AS_NEEDED', 'WEEKLY', 'EVERY_OTHER_DAY', 'BEFORE_FOOD', 'AFTER_FOOD', 'WITH_FOOD', name='intake_frequency_enum'), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('quantity_prescribed', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prescription_items_medicine_id', 'prescription_items', ['medicine_id'], unique=False)
    op.create_index('ix_prescription_items_prescription_id', 'prescription_items', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prescription_items_prescription_id', table_name='prescription_items')
    op.drop_index('ix_prescription_items_medicine_id', table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index('ix_scan_events_verdict', table_name='medicine_scan_events')
    op.drop_index('ix_scan_events_user_id', table_name='medicine_scan_events')
    op.drop_index('ix_scan_events_scanned_at', table_name='medicine_scan_events')
    op.drop_index('ix_scan_events_medicine_id', table_name='medicine_scan_events')
    op.drop_index('ix_scan_events_batch_id', table_name='medicine_scan_events')
    op.drop_index(op.f('ix_medicine_scan_events_user_id'), table_name='medicine_scan_events')
    op.drop_index(op.f('ix_medicine_scan_events_medicine_id'), table_name='medicine_scan_events')
    op.drop_index(op.f('ix_medicine_scan_events_batch_id'), table_name='medicine_scan_events')
    op.drop_index(op.f('ix_medicine_scan_events_authenticity_verdict'), table_name='medicine_scan_events')
    op.drop_table('medicine_scan_events')
    op.drop_index(op.f('ix_user_medical_conditions_user_id'), table_name='user_medical_conditions')
    op.drop_index('ix_user_conditions_user_id', table_name='user_medical_conditions')
    op.drop_index('ix_user_conditions_icd10', table_name='user_medical_conditions')
    op.drop_table('user_medical_conditions')
    op.drop_index(op.f('ix_user_health_profiles_user_id'), table_name='user_health_profiles')
    op.drop_table('user_health_profiles')
    op.drop_index(op.f('ix_user_drug_reactions_user_id'), table_name='user_drug_reactions')
    op.drop_index('ix_user_drug_reactions_salt_id', table_name='user_drug_reactions')
    op.drop_table('user_drug_reactions')
    op.drop_index('ix_user_allergies_user_id', table_name='user_allergies')
    op.drop_index('ix_user_allergies_category', table_name='user_allergies')
    op.drop_table('user_allergies')
    op.drop_index(op.f('ix_prescriptions_user_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index('ix_medicine_salts_salt_id', table_name='medicine_salts')
    op.drop_index(op.f('ix_medicine_salts_medicine_id'), table_name='medicine_salts')
    op.drop_table('medicine_salts')
    op.drop_index(op.f('ix_medicine_batches_medicine_id'), table_name='medicine_batches')
    op.drop_index(op.f('ix_medicine_batches_expiry_date'), table_name='medicine_batches')
    op.drop_index('ix_medicine_batches_expiry', table_name='medicine_batches')
    op.drop_index(op.f('ix_medicine_batches_batch_no'), table_name='medicine_batches')
    op.drop_index(op.f('ix_medicine_batches_barcode'), table_name='medicine_batches')
    op.drop_table('medicine_batches')
    op.drop_index('ix_grocery_ingredients_item_id', table_name='grocery_ingredients')
    op.drop_index(op.f('ix_grocery_ingredients_grocery_item_id'), table_name='grocery_ingredients')
    op.drop_index(op.f('ix_grocery_ingredients_allergen_category'), table_name='grocery_ingredients')
    op.drop_index('ix_grocery_ingredients_allergen', table_name='grocery_ingredients')
    op.drop_table('grocery_ingredients')
    op.drop_index('ix_drug_interactions_severity', table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_salt_id_b'), table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_salt_id_a'), table_name='drug_interactions')
    op.drop_index('ix_drug_interactions_b', table_name='drug_interactions')
    op.drop_index('ix_drug_interactions_a', table_name='drug_interactions')
    op.drop_table('drug_interactions')
    op.drop_index(op.f('ix_conversation_messages_whatsapp_user_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_direction'), table_name='conversation_messages')
    op.drop_index('ix_conv_messages_wa_id_created', table_name='conversation_messages')
    op.drop_index('ix_conv_messages_user_id_created', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_users_whatsapp_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_salts_name'), table_name='salts')
    op.drop_table('salts')
    op.drop_index(op.f('ix_product_certifications_product_type'), table_name='product_certifications')
    op.drop_index(op.f('ix_product_certifications_product_id'), table_name='product_certifications')
    op.drop_index('ix_product_certifications_product', table_name='product_certifications')
    op.drop_index(op.f('ix_product_certifications_license_number'), table_name='product_certifications')
    op.drop_index('ix_product_certifications_license', table_name='product_certifications')
    op.drop_index('ix_product_certifications_authority', table_name='product_certifications')
    op.drop_table('product_certifications')
    op.drop_index(op.f('ix_medicines_manufacturer'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_generic_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_cdsco_license'), table_name='medicines')
    op.drop_index('ix_medicines_cdsco', table_name='medicines')
    op.drop_index('ix_medicines_brand_name', table_name='medicines')
    op.drop_index(op.f('ix_medicines_barcode'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index(op.f('ix_grocery_items_product_name'), table_name='grocery_items')
    op.drop_index('ix_grocery_items_name', table_name='grocery_items')
    op.drop_index(op.f('ix_grocery_items_fssai_license'), table_name='grocery_items')
    op.drop_index('ix_grocery_items_fssai', table_name='grocery_items')
    op.drop_index('ix_grocery_items_category', table_name='grocery_items')
    op.drop_index(op.f('ix_grocery_items_brand_name'), table_name='grocery_items')
    op.drop_index('ix_grocery_items_barcode', table_name='grocery_items')
    op.drop_table('grocery_items')
    # ### end Alembic commands ###
